[package]
name = "shakechat-desktop"
version = "1.9.1"
description = "ShakeChat desktop client"
authors = ["ShakeThat"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
log = "0.4"
livekit = { version = "0.9.1", features = ["rustls-tls-native-roots"] }
parking_lot = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-updater = "2"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync", "time"] }

[features]
default = []
