import { FormEvent, useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, AtSign, Ban, CheckCircle2, CheckCheck, ChevronDown, Copy, Hash, History, Link2, Lock, LogOut, Menu, Paperclip, Pencil, Pin, Plus, Reply, Search, Send, Settings, ShieldCheck, SmilePlus, Trash2, Unlock, UserMinus, UserPlus, UserRound, Users, Volume2, X } from 'lucide-react';
import { api, auth, ApiError, BlockedUser, DirectConversation, DirectMessage, Friend, FriendRequests, Invite, InvitePreview, Member, Message, Permission, Server, ServerAuditAction, ServerAuditLog, ServerBan, User } from './api';
import { ChannelPermissionsSettings, RolesSettings } from './PermissionsSettings';
import { chatSocket, closeChatSocket } from './socket';
import { useChat } from './useChat';
import { DirectChat, FriendsHome, SocialSidebar } from './Social';
import { useDirectMessages } from './useDirectMessages';
import { useVoice } from './useVoice';
import { VoiceDock, VoicePanel } from './Voice';
import { ChannelOrganizer, MessageText, ProfileModal, ProfileModeDot, SearchPanel, profileModeLabel } from './V09Panels';
import { AppSettingsModal } from './AppSettings';
import { AppPreferences, applyPreferences, loadPreferences, persistPreferences } from './preferences';


function AppToasts({notice,error,onDismissNotice,onDismissError}:{notice:string;error:string;onDismissNotice:()=>void;onDismissError:()=>void}){
  if(!notice&&!error)return null;
  return <div className="toast-stack" aria-live="polite">{error&&<div className="toast error-toast" role="alert"><AlertTriangle size={18}/><span>{error}</span><button aria-label="Hatayı kapat" onClick={onDismissError}><X size={15}/></button></div>}{notice&&<div className="toast success-toast" role="status"><CheckCircle2 size={18}/><span>{notice}</span><button aria-label="Bildirimi kapat" onClick={onDismissNotice}><X size={15}/></button></div>}</div>;
}

function inviteCodeFromLocation() {
  const path = window.location.pathname.match(/^\/invite\/([^/]+)\/?$/);
  if (path) return decodeURIComponent(path[1]);
  const hash = window.location.hash.match(/^#\/invite\/([^/]+)\/?$/);
  return hash ? decodeURIComponent(hash[1]) : '';
}

function AuthScreen({ onAuth, inviteCode }:{onAuth:()=>void;inviteCode?:string}) {
  const [mode,setMode]=useState<'login'|'register'>('login');
  const [error,setError]=useState('');
  const [busy,setBusy]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){
    e.preventDefault(); if(busy)return; setBusy(true); setError(''); const f=new FormData(e.currentTarget);
    try {
      const r=mode==='login'
        ? await api.login(String(f.get('login')),String(f.get('password')))
        : await api.register(String(f.get('email')),String(f.get('username')),String(f.get('password')));
      auth.set(r.accessToken); onAuth();
    } catch(err:any){ setError(err.message); } finally { setBusy(false); }
  }
  return <div className="auth-bg"><form className="auth-card" onSubmit={submit}>
    <div className="brand-big">S</div><h1>ShakeChat</h1><p>Arkadaş grubunun özel iletişim alanı.</p>
    {inviteCode&&<div className="invite-auth-note"><UserPlus size={16}/> Davet bağlantısıyla geldin. Giriş yaptıktan sonra sunucuya katılabilirsin.</div>}
    {mode==='register' && <><input name="email" placeholder="E-posta" type="email" required/><input name="username" placeholder="Kullanıcı adı" required/></>}
    {mode==='login' && <input name="login" placeholder="Kullanıcı adı veya e-posta" required/>}
    <input name="password" placeholder="Şifre (en az 8 karakter)" type="password" minLength={8} required/>
    {error&&<div className="error">{error}</div>}
    <button disabled={busy}>{mode==='login'?'Giriş yap':'Hesap oluştur'}</button>
    <a onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Hesabın yok mu? Kayıt ol':'Zaten hesabın var mı? Giriş yap'}</a>
  </form></div>
}

type ModalState = null | { kind:'server' } | { kind:'channel'; initialType?:'TEXT'|'VOICE' };
function CreateModal({ modal, onClose, onCreateServer, onCreateChannel }:{
  modal: Exclude<ModalState,null>; onClose:()=>void;
  onCreateServer:(name:string)=>Promise<void>; onCreateChannel:(name:string,type:'TEXT'|'VOICE')=>Promise<void>;
}){
  const [name,setName]=useState('');
  const [type,setType]=useState<'TEXT'|'VOICE'>(modal.kind==='channel'?(modal.initialType||'TEXT'):'TEXT');
  const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{dialog.current?.showModal()},[]);
  async function submit(e:FormEvent){e.preventDefault();if(busy||!name.trim())return;setBusy(true);setError('');try{if(modal.kind==='server')await onCreateServer(name.trim());else await onCreateChannel(name.trim(),type);onClose()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  return <dialog ref={dialog} aria-labelledby="create-title" className="modal-backdrop" onCancel={e=>{e.preventDefault();if(!busy)onClose()}} onMouseDown={e=>{if(!busy&&e.currentTarget===e.target)onClose()}}>
    <form className="modal" onSubmit={submit}>
      <div className="modal-head"><div><h2 id="create-title">{modal.kind==='server'?'Sunucu oluştur':'Kanal oluştur'}</h2><p>{modal.kind==='server'?'Arkadaş grubun için yeni bir alan aç.':'Sunucuna yeni bir metin veya ses kanalı ekle.'}</p></div><button className="icon-btn" aria-label="Kapat" disabled={busy} type="button" onClick={onClose}><X size={20}/></button></div>
      <label htmlFor="create-name">AD</label><input id="create-name" required minLength={modal.kind==='server'?2:1} autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder={modal.kind==='server'?'Örn. Gece Tayfası':'Örn. genel-sohbet'} maxLength={64}/>
      {modal.kind==='channel'&&<div className="type-row"><button type="button" className={type==='TEXT'?'type-card selected':'type-card'} onClick={()=>setType('TEXT')}><Hash size={22}/><span><b>Metin kanalı</b><small>Yazılı sohbet</small></span></button><button type="button" className={type==='VOICE'?'type-card selected':'type-card'} onClick={()=>setType('VOICE')}><Volume2 size={22}/><span><b>Ses kanalı</b><small>Ses kanalı kaydı</small></span></button></div>}
      {error&&<div className="error">{error}</div>}
      <div className="modal-actions"><button type="button" className="ghost" disabled={busy} onClick={onClose}>İptal</button><button className="primary" disabled={busy||!name.trim()}>{busy?'Oluşturuluyor…':'Oluştur'}</button></div>
    </form>
  </dialog>;
}

function Avatar({user,online}:{user:User;online?:boolean}){
  return <div className={`avatar ${online?'online':''}`}>{user.avatarUrl?<img src={user.avatarUrl} alt="" onError={e=>{e.currentTarget.style.display='none'}}/>:(user.displayName||user.username).slice(0,2).toUpperCase()}</div>;
}

function StartupScreen({error,onRetry,onLogout}:{error?:string;onRetry?:()=>void;onLogout?:()=>void}){
  return <div className="startup-screen"><div className="startup-orbit"><span>ST</span><i/><i/><i/></div><div className="startup-copy"><small>SHAKECHAT · 1.9</small><h1>{error?'Alan açılamadı':'Alan hazırlanıyor'}</h1><p>{error||'Akışlar, arkadaşlar ve bağlantılar hazırlanıyor…'}</p>{error&&<div className="startup-actions"><button className="primary" onClick={onRetry}>Tekrar dene</button><button className="ghost" onClick={onLogout}>Çıkış yap</button></div>}</div></div>;
}

function InviteJoinModal({code,onClose,onJoined}:{code:string;onClose:()=>void;onJoined:(serverId:string)=>Promise<void>}){
  const [preview,setPreview]=useState<InvitePreview|null>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const dialog=useRef<HTMLDialogElement>(null);
  useEffect(()=>{dialog.current?.showModal();api.invitePreview(code).then(setPreview).catch((e:Error)=>setError(e.message))},[code]);
  async function join(){if(busy)return;setBusy(true);setError('');try{const result=await api.joinInvite(code);await onJoined(result.server.id);onClose()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  return <dialog ref={dialog} aria-labelledby="invite-title" className="modal-backdrop" onCancel={e=>{e.preventDefault();onClose()}}>
    <div className="modal invite-modal"><div className="modal-head"><div><h2 id="invite-title">Sunucu daveti</h2><p>Davet kodu: <code>{code}</code></p></div><button className="icon-btn" aria-label="Kapat" onClick={onClose}><X size={20}/></button></div>
      {error?<div className="error banner">{error}</div>:!preview?<div className="message-skeleton">Davet kontrol ediliyor…</div>:<div className="invite-preview"><div className="server-preview-icon">{preview.server.name.slice(0,2).toUpperCase()}</div><div><h3>{preview.server.name}</h3><p>{preview.server.memberCount} üye</p>{preview.expiresAt&&<small>Son kullanım: {new Date(preview.expiresAt).toLocaleString('tr-TR')}</small>}</div></div>}
      <div className="modal-actions"><button className="ghost" onClick={onClose}>İptal</button><button className="primary" disabled={!preview||busy||!!error} onClick={join}>{busy?'Katılınıyor…':'Sunucuya katıl'}</button></div>
    </div>
  </dialog>;
}

function inviteUrl(code:string){
  const origin=window.location.hostname==='tauri.localhost'?'https://chat.shakethat.com.tr':window.location.origin;
  return `${origin}/invite/${code}`;
}
function hasMention(content:string,username?:string){if(!username)return false;const escaped=username.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');return new RegExp(`(^|\\s)@${escaped}(?=$|\\s|[.,!?;:])`,'i').test(content)}
function directConversationLabel(conversation?:DirectConversation){if(!conversation)return 'Özel mesaj';if(!conversation.isGroup&&conversation.other)return conversation.other.displayName||conversation.other.username;if(conversation.title?.trim())return conversation.title.trim();return conversation.members.slice(0,3).map(user=>user.displayName||user.username).join(', ')||'Grup sohbeti'}

function ServerSettingsModal({server,members,me,permissions,onClose,onLeave,onKick,onChanged}:{server:Server;members:Member[];me:User;permissions:Permission[];onClose:()=>void;onLeave:()=>Promise<void>;onKick:(id:string)=>Promise<void>;onChanged:()=>void}){
  const [tab,setTab]=useState<'members'|'invites'|'bans'|'audit'|'roles'|'channelPermissions'|'flows'>('members'); const [invites,setInvites]=useState<Invite[]>([]); const [bans,setBans]=useState<ServerBan[]>([]); const [audit,setAudit]=useState<ServerAuditLog[]>([]); const [auditAction,setAuditAction]=useState<ServerAuditAction|''>(''); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [expires,setExpires]=useState('24'); const [maxUses,setMaxUses]=useState(''); const [confirmKick,setConfirmKick]=useState(''); const [confirmLeave,setConfirmLeave]=useState(false); const dialog=useRef<HTMLDialogElement>(null);
  const meMember=members.find(member=>member.id===me.id); const isOwner=meMember?.role==='OWNER'; const has=(permission:Permission)=>isOwner||permissions.includes('ADMINISTRATOR')||permissions.includes(permission); const canInvites=has('MANAGE_INVITES'); const canRoles=has('MANAGE_ROLES'); const canKick=has('KICK_MEMBERS'); const canBan=has('BAN_MEMBERS'); const canModerate=has('MODERATE_MEMBERS'); const canChannels=has('MANAGE_CHANNELS'); const canAudit=has('MANAGE_SERVER')||canKick||canBan||canModerate;
  useEffect(()=>{dialog.current?.showModal()},[]);
  useEffect(()=>{if(tab==='invites'&&canInvites){setLoading(true);api.invites(server.id).then(setInvites).catch((e:Error)=>setError(e.message)).finally(()=>setLoading(false))}else if(tab==='bans'&&canBan){setLoading(true);api.bans(server.id).then(setBans).catch((e:Error)=>setError(e.message)).finally(()=>setLoading(false))}else if(tab==='audit'&&canAudit){setLoading(true);api.auditLogs(server.id,auditAction||undefined).then(setAudit).catch((e:Error)=>setError(e.message)).finally(()=>setLoading(false))}},[tab,server.id,canInvites,canBan,canAudit,auditAction]);
  async function createInvite(){setLoading(true);setError('');try{const created=await api.createInvite(server.id,{expiresInHours:expires?Number(expires):undefined,maxUses:maxUses?Number(maxUses):undefined});setInvites(previous=>[created,...previous])}catch(e:any){setError(e.message)}finally{setLoading(false)}}
  async function revoke(invite:Invite){setError('');try{await api.revokeInvite(server.id,invite.id);setInvites(previous=>previous.map(item=>item.id===invite.id?{...item,revokedAt:new Date().toISOString()}:item))}catch(e:any){setError(e.message)}}
  async function copy(code:string){try{await navigator.clipboard.writeText(inviteUrl(code))}catch{setError('Bağlantı panoya kopyalanamadı.')}}
  async function banMember(member:Member){const reason=prompt(`${member.displayName||member.username} için yasak nedeni (isteğe bağlı)`,'');if(reason===null)return;setError('');try{await api.banMember(server.id,member.id,reason);setBans(await api.bans(server.id));onChanged()}catch(e){setError((e as Error).message)}}
  async function unbanMember(userId:string){setError('');try{await api.unbanMember(server.id,userId);setBans(previous=>previous.filter(item=>item.userId!==userId));onChanged()}catch(e){setError((e as Error).message)}}
  async function restrictMember(member:Member){const raw=prompt(`${member.displayName||member.username} kaç dakika yazamasın? (1–10080)`,'60');if(raw===null)return;const minutes=Math.trunc(Number(raw));if(!Number.isFinite(minutes)||minutes<1||minutes>10080){setError('Süre 1 ile 10080 dakika arasında olmalı.');return}const reason=prompt('Kısıtlama nedeni (isteğe bağlı)','');if(reason===null)return;setError('');try{await api.restrictMemberMessages(server.id,member.id,minutes,reason);onChanged()}catch(e){setError((e as Error).message)}}
  async function clearRestriction(member:Member){setError('');try{await api.clearMemberMessageRestriction(server.id,member.id);onChanged()}catch(e){setError((e as Error).message)}}
  const restrictionActive=(member:Member)=>!!member.messageRestrictedUntil&&new Date(member.messageRestrictedUntil).getTime()>Date.now();
  const title=tab==='members'?'Alan üyeleri':tab==='invites'?'Davet bağlantıları':tab==='bans'?'Yasaklı kullanıcılar':tab==='audit'?'İşlem geçmişi':tab==='roles'?'Roller ve izinler':tab==='channelPermissions'?'Akış izinleri':'Akış düzeni';
  const auditText=(item:ServerAuditLog)=>item.action==='MEMBER_KICKED'?`${item.actorName} → ${item.targetName} · Alandan çıkarıldı`:item.action==='MEMBER_BANNED'?`${item.actorName} → ${item.targetName} · Yasaklandı`:item.action==='MEMBER_UNBANNED'?`${item.actorName} → ${item.targetName} · Yasak kaldırıldı`:item.action==='MEMBER_RESTRICTED'?`${item.actorName} → ${item.targetName} · Yazma kısıtı uygulandı`:`${item.actorName} → ${item.targetName} · Yazma kısıtı kaldırıldı`;
  return <dialog ref={dialog} aria-label="Sunucu üyeleri" className="modal-backdrop settings-backdrop" onCancel={e=>{e.preventDefault();onClose()}}>
    <div className="settings-modal"><aside><h3>{server.name}</h3><button className={tab==='members'?'selected':''} onClick={()=>setTab('members')}>Üyeler</button><button className={tab==='invites'?'selected':''} onClick={()=>setTab('invites')}>Davetler</button>{canBan&&<button className={tab==='bans'?'selected':''} onClick={()=>setTab('bans')}>Yasaklılar</button>}{canAudit&&<button className={tab==='audit'?'selected':''} onClick={()=>setTab('audit')}><History size={14}/> İşlem geçmişi</button>}{canChannels&&<button className={tab==='flows'?'selected':''} onClick={()=>setTab('flows')}>Akış düzeni</button>}{canRoles&&<><button className={tab==='roles'?'selected':''} onClick={()=>setTab('roles')}>Roller</button><button className={tab==='channelPermissions'?'selected':''} onClick={()=>setTab('channelPermissions')}>Akış izinleri</button></>}<div className="settings-spacer"/><button className="danger-link" onClick={()=>setConfirmLeave(true)} disabled={!meMember||isOwner}>Sunucudan ayrıl</button></aside>
      <section><div className="modal-head"><div><h2 id="settings-title">{title}</h2><p>{tab==='members'?`${members.length} üye`:tab==='invites'?'Arkadaşlarını ShakeChat’e davet et.':tab==='bans'?'Bu alana yeniden katılamayacak kullanıcıları yönet.':tab==='audit'?'Son 100 moderasyon işlemini kim, kime ve ne zaman yaptı görüntüle.':tab==='roles'?'Rolleri oluştur, üyelere ata ve alan izinlerini yönet.':tab==='channelPermissions'?'Rol bazında akış izinlerini değiştir.':'Akışları bölümlere ayır ve sıralarını değiştir.'}</p></div><button className="icon-btn" aria-label="Kapat" onClick={onClose}><X size={20}/></button></div>
        {error&&<div className="error banner">{error}</div>}
        {tab==='members'?<div className="settings-list">{members.map(member=><div className="settings-row" key={member.id}><Avatar user={member} online={member.online}/><div className="grow"><b>{member.displayName||member.username}</b><small>{(member.roles?.map(role=>role.name).join(' · '))||(member.role==='OWNER'?'Sunucu sahibi':member.role==='ADMIN'?'Yönetici':member.role==='MODERATOR'?'Moderatör':'Üye')}{member.id===me.id?' · Sen':''}{restrictionActive(member)?` · Yazma kısıtı ${new Date(member.messageRestrictedUntil!).toLocaleString('tr-TR')}'e kadar${member.messageRestrictionReason?` · ${member.messageRestrictionReason}`:''}`:''}</small></div>{canModerate&&member.id!==me.id&&member.role!=='OWNER'&&member.role!=='ADMIN'&&(restrictionActive(member)?<button className="ghost-small" onClick={()=>void clearRestriction(member)}>Kısıtı kaldır</button>:<button className="ghost-small" onClick={()=>void restrictMember(member)}>Yazmayı kısıtla</button>)}{canKick&&member.id!==me.id&&member.role!=='OWNER'&&(confirmKick===member.id?<><button className="danger" onClick={()=>{setError('');onKick(member.id).then(()=>setConfirmKick('')).catch((e:Error)=>setError(e.message))}}>Evet, çıkar</button><button className="ghost-small" onClick={()=>setConfirmKick('')}>Vazgeç</button></>:<button className="ghost-small" onClick={()=>setConfirmKick(member.id)}><UserMinus size={15}/> Çıkar</button>)}{canBan&&member.id!==me.id&&member.role!=='OWNER'&&<button className="ghost-small danger-text" onClick={()=>void banMember(member)}><Ban size={15}/> Yasakla</button>}</div>)}</div>:
        tab==='invites'?(!canInvites?<div className="empty settings-empty"><Link2 size={36}/><h3>Davet yönetimi yetkin yok</h3></div>:<><div className="invite-builder"><label>SÜRE<select value={expires} onChange={e=>setExpires(e.target.value)}><option value="1">1 saat</option><option value="24">24 saat</option><option value="168">7 gün</option><option value="">Süresiz</option></select></label><label>KULLANIM SINIRI<input inputMode="numeric" min="1" max="1000" value={maxUses} onChange={e=>setMaxUses(e.target.value.replace(/\D/g,'').slice(0,4))} placeholder="Sınırsız"/></label><button className="primary compact" disabled={loading} onClick={createInvite}><UserPlus size={16}/> Davet oluştur</button></div><div className="settings-list">{loading&&invites.length===0?<div className="message-skeleton">Davetler yükleniyor…</div>:invites.length===0?<div className="empty settings-empty"><Link2 size={34}/><p>Henüz davet oluşturulmadı.</p></div>:invites.map(invite=><div className={`invite-row ${invite.revokedAt?'revoked':''}`} key={invite.id}><div className="grow"><code>{invite.code}</code><small>{invite.revokedAt?'İptal edildi':invite.expiresAt&&new Date(invite.expiresAt).getTime()<Date.now()?'Süresi doldu':'Aktif'} · {invite.useCount}/{invite.maxUses??'∞'} kullanım · {invite.creator?.username||'?'}</small></div><button className="ghost-small" title="Bağlantıyı kopyala" onClick={()=>copy(invite.code)} disabled={!!invite.revokedAt}><Copy size={15}/></button><button className="ghost-small danger-text" title="Daveti iptal et" onClick={()=>revoke(invite)} disabled={!!invite.revokedAt}><Trash2 size={15}/></button></div>)}</div></>):
        tab==='bans'?(!canBan?<div className="empty settings-empty"><Ban size={36}/><h3>Yasak yönetimi yetkin yok</h3></div>:<div className="settings-list">{loading&&bans.length===0?<div className="message-skeleton">Yasaklılar yükleniyor…</div>:bans.length===0?<div className="empty settings-empty"><Ban size={34}/><p>Yasaklı kullanıcı yok.</p></div>:bans.map(item=><div className="settings-row" key={item.id}><Avatar user={item.user}/><div className="grow"><b>{item.user.displayName||item.user.username}</b><small>{item.reason||'Neden belirtilmedi'} · {new Date(item.createdAt).toLocaleDateString('tr-TR')}</small></div><button className="ghost-small" onClick={()=>void unbanMember(item.userId)}>Yasağı kaldır</button></div>)}</div>):tab==='audit'?(!canAudit?<div className="empty settings-empty"><History size={36}/><h3>İşlem geçmişini görme yetkin yok</h3></div>:<><div className="audit-toolbar"><label>İŞLEM TÜRÜ<select aria-label="İŞLEM TÜRÜ" value={auditAction} onChange={e=>setAuditAction(e.target.value as ServerAuditAction|'')}><option value="">Tümü</option><option value="MEMBER_KICKED">Çıkarma</option><option value="MEMBER_BANNED">Yasaklama</option><option value="MEMBER_UNBANNED">Yasak kaldırma</option><option value="MEMBER_RESTRICTED">Yazma kısıtı</option><option value="MEMBER_RESTRICTION_REMOVED">Kısıt kaldırma</option></select></label><small>En yeni 100 kayıt</small></div><div className="settings-list audit-list">{loading&&audit.length===0?<div className="message-skeleton">İşlem geçmişi yükleniyor…</div>:audit.length===0?<div className="empty settings-empty"><History size={34}/><p>Henüz moderasyon kaydı yok.</p></div>:audit.map(item=><div className="audit-row" key={item.id}><div className={`audit-mark ${item.action.toLowerCase()}`}><History size={15}/></div><div className="grow"><b>{auditText(item)}</b><small>{new Date(item.createdAt).toLocaleString('tr-TR')}{item.reason?` · Neden: ${item.reason}`:''}</small></div></div>)}</div></>):tab==='roles'?<RolesSettings server={server} members={members} me={me} onChanged={onChanged}/>:tab==='channelPermissions'?<ChannelPermissionsSettings server={server} onChanged={onChanged}/>:<ChannelOrganizer server={server} onChanged={onChanged}/>} 
        {confirmLeave&&<div className="confirm-strip"><span>Bu sunucudan ayrılmak istediğine emin misin?</span><button className="danger" onClick={()=>{setError('');onLeave().then(onClose).catch((e:Error)=>setError(e.message))}}>Evet, ayrıl</button><button className="ghost-small" onClick={()=>setConfirmLeave(false)}>Vazgeç</button></div>}
      </section>
    </div>
  </dialog>;
}

export function App(){
  const [authed,setAuthed]=useState(!!auth.token()); const [me,setMe]=useState<User|null>(null); const [servers,setServers]=useState<Server[]>([]); const [serverId,setServerId]=useState(''); const [channelId,setChannelId]=useState(''); const [drafts,setDrafts]=useState<Record<string,string>>({}); const [sending,setSending]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [modal,setModal]=useState<ModalState>(null); const [showChannels,setShowChannels]=useState(false); const [settingsOpen,setSettingsOpen]=useState(false); const [pendingInvite,setPendingInvite]=useState(inviteCodeFromLocation());
  const [replyTo,setReplyTo]=useState<Message|null>(null); const [pendingFiles,setPendingFiles]=useState<File[]>([]); const [editingId,setEditingId]=useState('');
  const [accessPermissions,setAccessPermissions]=useState<Permission[]>([]);
  const [view,setView]=useState<'server'|'home'>('server'); const [friends,setFriends]=useState<Friend[]>([]); const [friendRequests,setFriendRequests]=useState<FriendRequests>({incoming:[],outgoing:[]}); const [blocked,setBlocked]=useState<BlockedUser[]>([]); const [conversations,setConversations]=useState<DirectConversation[]>([]); const [activeDmId,setActiveDmId]=useState(''); const [dmDrafts,setDmDrafts]=useState<Record<string,string>>({}); const [dmSending,setDmSending]=useState(false);
  const [profileOpen,setProfileOpen]=useState(false); const [searchOpen,setSearchOpen]=useState(false); const [appSettingsOpen,setAppSettingsOpen]=useState(false); const [moderationOpen,setModerationOpen]=useState(false); const [actionBusy,setActionBusy]=useState(''); const [unread,setUnread]=useState<Record<string,{count:number;mentions:number}>>({}); const [dmUnread,setDmUnread]=useState<Record<string,number>>({}); const [highlightMessageId,setHighlightMessageId]=useState('');
  const [notificationsEnabled,setNotificationsEnabled]=useState(()=>typeof Notification!=='undefined'&&Notification.permission==='granted'&&localStorage.getItem('shakechat.notifications.v09')==='1');
  const [preferences,setPreferences]=useState<AppPreferences>(()=>loadPreferences()); const [booting,setBooting]=useState(!!auth.token()); const [bootError,setBootError]=useState(''); const [bootAttempt,setBootAttempt]=useState(0);
  const scroll=useRef<HTMLElement>(null); const nearBottom=useRef(true); const composer=useRef<HTMLTextAreaElement>(null); const fileInput=useRef<HTMLInputElement>(null); const requestId=useRef(0);
  const server=useMemo(()=>servers.find(s=>s.id===serverId),[servers,serverId]); const channel=server?.channels.find(c=>c.id===channelId); const text=drafts[channelId]||''; const activeDm=conversations.find(conversation=>conversation.id===activeDmId); const dmText=dmDrafts[activeDmId]||'';
  const groupedChannels=useMemo(()=>{const groups=new Map<string,NonNullable<typeof server>['channels']>();for(const item of [...(server?.channels||[])].sort((a,b)=>a.position-b.position)){const label=item.groupName?.trim()||(item.type==='VOICE'?'Ses Alanı':'Sohbet');const bucket=groups.get(label)||[];bucket.push(item);groups.set(label,bucket)}return [...groups.entries()].map(([label,channels])=>({label,channels}))},[server]);
  const dmUnreadTotal=useMemo(()=>Object.values(dmUnread).reduce((sum,count)=>sum+count,0),[dmUnread]);
  const channelUnreadTotal=useMemo(()=>Object.values(unread).reduce((sum,item)=>sum+item.count,0),[unread]);
  const attentionTotal=dmUnreadTotal+channelUnreadTotal+friendRequests.incoming.length;
  const currentServerUnread=useMemo(()=>server?.channels.reduce((sum,item)=>sum+(unread[item.id]?.count||0),0)||0,[server,unread]);

  function chooseServer(list:Server[],id?:string){const chosen=(id&&list.find(s=>s.id===id))||list[0];setServerId(chosen?.id||'');setChannelId(chosen?.channels.find(c=>c.type==='TEXT')?.id||chosen?.channels[0]?.id||'')}
  function removeServerLocally(id:string,reason:'left'|'kicked'|'banned'){setServers(previous=>{const next=previous.filter(s=>s.id!==id);if(serverId===id)chooseServer(next);return next});setSettingsOpen(false);setNotice(reason==='banned'?'Bu sunucudan yasaklandın.':reason==='kicked'?'Bu sunucudan çıkarıldın.':'Sunucudan ayrıldın.')}
  const {messages,members,typingUsers,socketOnline,loading,announceTyping,appendSent}=useChat(authed,view==='server'?serverId:'',view==='server'&&channel?.type==='TEXT'?channelId:'',me?.id||'',setError,removeServerLocally,()=>{void reloadAccess()});
  const mentionMatch=text.match(/(?:^|\s)@([A-Za-z0-9_.-]*)$/); const mentionCandidates=mentionMatch?members.filter(member=>member.id!==me?.id&&member.username.toLowerCase().startsWith(mentionMatch[1].toLowerCase())).slice(0,5):[];
  const {messages:dmMessages,typingUsers:dmTypingUsers,loading:dmLoading,announceTyping:announceDmTyping,appendSent:appendDmSent}=useDirectMessages(authed,view==='home'?activeDmId:'',me?.id||'',setError);
  const voice=useVoice(authed,setError,preferences);
  const voiceChannelName=useMemo(()=>{for(const item of servers){const found=item.channels.find(c=>c.id===voice.channelId);if(found)return `${item.name} / ${found.name}`}return ''},[servers,voice.channelId]);

  function logout(){requestId.current++;void voice.leave();closeChatSocket();auth.clear();setAuthed(false);setMe(null);setServers([]);setServerId('');setChannelId('');setDrafts({});setFriends([]);setFriendRequests({incoming:[],outgoing:[]});setBlocked([]);setConversations([]);setActiveDmId('');setDmDrafts({});setUnread({});setDmUnread({});setProfileOpen(false);setSearchOpen(false);setAppSettingsOpen(false);setModal(null);setBooting(false);setBootError('');setError('')}
  useEffect(()=>{if(!authed)return;let active=true;const attempt=++requestId.current;setBooting(true);setBootError('');Promise.all([api.me(),api.servers(),api.friends(),api.friendRequests(),api.blockedUsers(),api.dms(),api.dmUnreads()]).then(([user,list,friendList,requests,blockedList,dms,dmRows])=>{if(!active||attempt!==requestId.current)return;setMe(user);setServers(list);setFriends(friendList);setFriendRequests(requests);setBlocked(blockedList);setConversations(dms);setDmUnread(Object.fromEntries(dmRows.map(row=>[row.conversationId,row.count])));chooseServer(list);void refreshUnreadCounts(list);setBooting(false)}).catch((e:Error)=>{if(!active)return;if(e instanceof ApiError&&e.status===401){logout();return}setBootError(e.message);setBooting(false)});return()=>{active=false}},[authed,bootAttempt]);
  useEffect(()=>{const expired=()=>logout();window.addEventListener('shakechat:session-expired',expired);return()=>window.removeEventListener('shakechat:session-expired',expired)},[]);
  useEffect(()=>{applyPreferences(preferences)},[preferences]);
  useEffect(()=>{const syncLogout=(e:StorageEvent)=>{if(e.key==='token'&&!e.newValue)logout()};window.addEventListener('storage',syncLogout);return()=>window.removeEventListener('storage',syncLogout)},[]);
  useEffect(()=>{if(!authed||view!=='server'||!serverId){setAccessPermissions([]);return}let active=true;api.myPermissions(serverId,channelId||undefined).then(result=>{if(active)setAccessPermissions(result.permissions)}).catch((e:Error)=>{if(active)setError(e.message)});return()=>{active=false}},[authed,view,serverId,channelId]);
  useEffect(()=>{
    if(!authed)return;
    const socket=chatSocket();
    const refresh=()=>{Promise.all([api.friends(),api.friendRequests(),api.blockedUsers(),api.dms()]).then(([friendList,requests,blockedList,dms])=>{setFriends(friendList);setFriendRequests(requests);setBlocked(blockedList);setConversations(previous=>{const active=previous.find(item=>item.id===activeDmId);return active&&!dms.some(item=>item.id===active.id)?[active,...dms]:dms})}).catch((e:Error)=>setError(e.message))};
    const presence=(data:{userId:string;online:boolean})=>setFriends(previous=>previous.map(friend=>friend.id===data.userId?{...friend,online:data.online}:friend));
    const conversationUpdate=(data:{conversationId:string;message?:DirectMessage;kind?:'new'|'update'|'delete'|'conversation'})=>{
      refresh();
      const message=data?.message;
      if((data.kind&&data.kind!=='new')||!message||!me||message.author.id===me.id)return;
      const active=view==='home'&&activeDmId===data.conversationId&&!document.hidden&&document.hasFocus();
      if(active){clearDmUnread(data.conversationId);return}
      setDmUnread(previous=>({...previous,[data.conversationId]:(previous[data.conversationId]||0)+1}));
      if(notificationsEnabled&&typeof Notification!=='undefined'&&Notification.permission==='granted'&&(document.hidden||!document.hasFocus())){
        const conversation=conversations.find(item=>item.id===data.conversationId);
        const notification=new Notification('ShakeChat · Özel mesaj',{body:`${message.author.displayName||message.author.username} · ${directConversationLabel(conversation)}
${message.content?.trim()||((message.attachments?.length||0)>0?`${message.attachments?.length} dosya paylaştı`:'Yeni mesaj')}`.slice(0,220)});
        notification.onclick=()=>{window.focus();setView('home');setActiveDmId(data.conversationId);clearDmUnread(data.conversationId);notification.close()};
      }
    };
    const refreshDmCounts=()=>{void api.dmUnreads().then(rows=>setDmUnread(Object.fromEntries(rows.map(row=>[row.conversationId,row.count])))).catch(()=>{})};
    socket.on('friend:presence',presence);socket.on('friend:request',refresh);socket.on('friendship:changed',refresh);socket.on('dm:conversation-update',conversationUpdate);
    const snapshot=()=>{socket.timeout(5000).emit('friends:snapshot',{},(_err:Error|null,reply:{ok:boolean;friends?:Array<{id:string;online:boolean}>})=>{if(reply?.ok)setFriends(previous=>previous.map(friend=>({...friend,online:reply.friends?.find(item=>item.id===friend.id)?.online??friend.online}))) });refreshDmCounts()};
    socket.on('connect',snapshot);if(socket.connected)snapshot();
    return()=>{socket.off('friend:presence',presence);socket.off('friend:request',refresh);socket.off('friendship:changed',refresh);socket.off('dm:conversation-update',conversationUpdate);socket.off('connect',snapshot)};
  },[authed,activeDmId,view,me?.id,notificationsEnabled,conversations]);
  useEffect(()=>{nearBottom.current=true;setError('');setNotice('');setReplyTo(null);setPendingFiles([]);setEditingId('')},[channelId]);
  useEffect(()=>{if(nearBottom.current&&scroll.current)scroll.current.scrollTop=scroll.current.scrollHeight},[messages,loading]);
  useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),3600);return()=>clearTimeout(t)},[notice]);
  useEffect(()=>{if(!error)return;const t=setTimeout(()=>setError(''),6500);return()=>clearTimeout(t)},[error]);
  useEffect(()=>{setModerationOpen(false)},[channelId,view]);
  useEffect(()=>{if(!moderationOpen)return;const close=()=>setModerationOpen(false);const key=(event:KeyboardEvent)=>{if(event.key==='Escape')setModerationOpen(false)};document.addEventListener('pointerdown',close);window.addEventListener('keydown',key);return()=>{document.removeEventListener('pointerdown',close);window.removeEventListener('keydown',key)}},[moderationOpen]);
  useEffect(()=>{document.title=attentionTotal>0?`(${Math.min(attentionTotal,99)}) ShakeChat`:'ShakeChat'},[attentionTotal]);
  useEffect(()=>{const visible=()=>{if(document.hidden)return;if(view==='server'&&channel?.type==='TEXT'&&channelId)clearUnread(channelId);if(view==='home'&&activeDmId)clearDmUnread(activeDmId)};visible();document.addEventListener('visibilitychange',visible);window.addEventListener('focus',visible);return()=>{document.removeEventListener('visibilitychange',visible);window.removeEventListener('focus',visible)}},[view,channelId,channel?.type,activeDmId]);
  useEffect(()=>{const shortcuts=(event:KeyboardEvent)=>{if(!(event.ctrlKey||event.metaKey))return;if(event.key.toLowerCase()==='k'&&server){event.preventDefault();setSearchOpen(true)}else if(event.key===','){event.preventDefault();setAppSettingsOpen(true)}};window.addEventListener('keydown',shortcuts);return()=>window.removeEventListener('keydown',shortcuts)},[server]);

  useEffect(()=>{if(!authed)return;const socket=chatSocket();const activity=(data:{serverId:string;channelId:string;messageId?:string;authorId?:string;authorName?:string;preview?:string;mentioned?:boolean})=>{if(!me||data.authorId===me.id)return;const active=view==='server'&&channelId===data.channelId&&!document.hidden&&document.hasFocus();if(active){setUnread(previous=>({...previous,[data.channelId]:{count:0,mentions:0}}));void api.markChannelRead(data.channelId).catch(()=>{});return}setUnread(previous=>{const current=previous[data.channelId]||{count:0,mentions:0};return {...previous,[data.channelId]:{count:current.count+1,mentions:current.mentions+(data.mentioned?1:0)}}});if(notificationsEnabled&&typeof Notification!=='undefined'&&Notification.permission==='granted'&&(document.hidden||!document.hasFocus())){const source=servers.find(item=>item.id===data.serverId);const flow=source?.channels.find(item=>item.id===data.channelId);const notification=new Notification(data.mentioned?'ShakeChat · Sana seslendi':'ShakeChat · Yeni mesaj',{body:`${data.authorName||'Bir üye'} · ${flow?.name||'akış'}\n${data.preview||'Yeni mesaj'}`});notification.onclick=()=>{window.focus();const target=servers.find(item=>item.id===data.serverId);if(target){setServerId(target.id);setView('server');setChannelId(data.channelId);clearUnread(data.channelId)}notification.close()}}};socket.on('channel:activity',activity);return()=>{socket.off('channel:activity',activity)}},[authed,me?.id,view,channelId,notificationsEnabled,servers]);
  useEffect(()=>{if(!highlightMessageId)return;const target=document.getElementById(`msg-${highlightMessageId}`);if(target)target.scrollIntoView({behavior:'smooth',block:'center'});const timer=setTimeout(()=>setHighlightMessageId(''),2400);return()=>clearTimeout(timer)},[messages,highlightMessageId]);
  useEffect(()=>{if(!authed||view!=='server'||!channelId||channel?.type!=='TEXT')return;setUnread(previous=>({...previous,[channelId]:{count:0,mentions:0}}));void api.markChannelRead(channelId).catch(()=>{})},[authed,view,channelId,channel?.type]);

  const can=(permission:Permission)=>members.some(member=>member.id===me?.id&&member.role==='OWNER')||accessPermissions.includes('ADMINISTRATOR')||accessPermissions.includes(permission);
  const channelLocked=channel?.type==='TEXT'&&!!channel.isLocked;
  const canBypassChannelLock=can('MANAGE_MESSAGES')||can('MANAGE_CHANNELS');
  const canSendCurrent=can('SEND_MESSAGES')&&(!channelLocked||canBypassChannelLock);
  async function refreshUnreadCounts(list:Server[]=servers){
    if(!authed||!list.length){if(!list.length)setUnread({});return}
    const results=await Promise.all(list.map(async item=>{try{return await api.unreads(item.id)}catch{return []}}));
    const next:Record<string,{count:number;mentions:number}>={};for(const rows of results)for(const row of rows)next[row.channelId]={count:row.count,mentions:row.mentions};setUnread(next);
  }
  function clearUnread(channel:string){setUnread(previous=>({...previous,[channel]:{count:0,mentions:0}}));void api.markChannelRead(channel).catch(()=>{})}
  async function refreshDmUnreadCounts(){if(!authed){setDmUnread({});return}try{const rows=await api.dmUnreads();setDmUnread(Object.fromEntries(rows.map(row=>[row.conversationId,row.count])))}catch{/* Badges should not block chat. */}}
  function clearDmUnread(conversationId:string){if(!conversationId)return;setDmUnread(previous=>({...previous,[conversationId]:0}));void api.markDmRead(conversationId).catch(()=>{})}
  async function markAllDmRead(){const ids=Object.entries(dmUnread).filter(([,count])=>count>0).map(([id])=>id);if(!ids.length)return;await Promise.allSettled(ids.map(id=>api.markDmRead(id)));setDmUnread({});setNotice('Özel mesajların tamamı okundu işaretlendi.')}
  async function markServerRead(){if(!server)return;const ids=server.channels.filter(item=>item.type==='TEXT'&&(unread[item.id]?.count||0)>0).map(item=>item.id);if(!ids.length)return;await Promise.allSettled(ids.map(id=>api.markChannelRead(id)));setUnread(previous=>{const next={...previous};for(const id of ids)next[id]={count:0,mentions:0};return next});setNotice('Bu alandaki okunmamışlar temizlendi.')}
  async function toggleNotifications(){
    if(notificationsEnabled){localStorage.removeItem('shakechat.notifications.v09');setNotificationsEnabled(false);setNotice('Masaüstü bildirimleri kapatıldı.');return}
    if(typeof Notification==='undefined'){setError('Bu tarayıcı masaüstü bildirimlerini desteklemiyor.');return}
    const permission=Notification.permission==='granted'?'granted':await Notification.requestPermission();
    if(permission==='granted'){localStorage.setItem('shakechat.notifications.v09','1');setNotificationsEnabled(true);setNotice('Masaüstü bildirimleri açıldı.')}else setError('Tarayıcı bildirim izni vermedi.')
  }
  function insertMention(username:string){if(!mentionMatch)return;const start=text.lastIndexOf('@');const next=`${text.slice(0,start)}@${username} `;changeDraft(next);requestAnimationFrame(()=>composer.current?.focus())}
  function pickSearchResult(result:{channelId:string;id:string}){setSearchOpen(false);setView('server');selectChannel(result.channelId);setHighlightMessageId(result.id);setNotice('Arama sonucunun bulunduğu akış açıldı.')}
  async function reloadAccess(){if(!serverId)return;try{const list=await api.servers();setServers(list);void refreshUnreadCounts(list);const current=list.find(item=>item.id===serverId);if(!current){chooseServer(list);return}const nextChannel=current.channels.some(item=>item.id===channelId)?channelId:(current.channels.find(item=>item.type==='TEXT')?.id||current.channels[0]?.id||'');if(nextChannel!==channelId)setChannelId(nextChannel);const result=await api.myPermissions(serverId,nextChannel||undefined);setAccessPermissions(result.permissions)}catch(e){setError((e as Error).message)}}
  async function refreshServers(preferred?:string){const list=await api.servers();setServers(list);chooseServer(list,preferred);void refreshUnreadCounts(list)}
  async function createServer(name:string){const created=await api.createServer(name);setServers(previous=>[...previous,created]);setServerId(created.id);const first=created.channels.find(c=>c.type==='TEXT')?.id||'';setChannelId(first);if(first)clearUnread(first)}
  async function createChannel(name:string,type:'TEXT'|'VOICE'){if(!server)throw new Error('Önce bir sunucu seç.');const id=server.id;const created=await api.createChannel(id,name,type);setServers(previous=>previous.map(s=>s.id===id?{...s,channels:[...s.channels,created]}:s));setChannelId(created.id);if(created.type==='VOICE')void voice.join(created.id)}
  async function deleteChannel(){if(actionBusy||!server||!channel||!can('MANAGE_CHANNELS'))return;if(!confirm(`#${channel.name} kanalı silinsin mi? Mesajları da silinir.`))return;setActionBusy('delete-channel');setModerationOpen(false);try{await api.deleteChannel(server.id,channel.id);await reloadAccess();setNotice('Kanal silindi.')}catch(e){setError((e as Error).message)}finally{setActionBusy('')}}
  async function toggleChannelLock(){if(actionBusy||!server||!channel||channel.type!=='TEXT'||!can('MANAGE_CHANNELS'))return;const next=!channel.isLocked;setActionBusy('channel-lock');try{await api.updateChannel(server.id,channel.id,{isLocked:next});await reloadAccess();setNotice(next?'Akış kilitlendi. Yalnızca moderasyon yazabilir.':'Akış kilidi açıldı.')}catch(e){setError((e as Error).message)}finally{setActionBusy('')}}
  async function changeSlowMode(seconds:number){if(actionBusy||!server||!channel||channel.type!=='TEXT'||!can('MANAGE_CHANNELS'))return;setActionBusy('slow-mode');try{await api.updateChannel(server.id,channel.id,{slowModeSeconds:seconds});await reloadAccess();setNotice(seconds>0?`Mesaj aralığı ${seconds} saniye olarak ayarlandı.`:'Mesaj aralığı kapatıldı.')}catch(e){setError((e as Error).message)}finally{setActionBusy('')}}
  async function bulkDeleteMessages(){if(actionBusy||!channelId||channel?.type!=='TEXT'||!can('MANAGE_MESSAGES'))return;const raw=prompt('Son kaç mesaj temizlensin? (2-100)','20');if(raw===null)return;const count=Number(raw);if(!Number.isInteger(count)||count<2||count>100){setError('Temizlenecek mesaj sayısı 2 ile 100 arasında tam sayı olmalı.');return}if(!confirm(`Bu akıştaki son ${count} mesaj kalıcı olarak silinsin mi?`))return;setActionBusy('bulk-delete');setModerationOpen(false);try{const result=await api.bulkDeleteMessages(channelId,count);setNotice(`${result.count} mesaj temizlendi.`)}catch(e){setError((e as Error).message)}finally{setActionBusy('')}}
  async function deleteMessage(messageId:string){if(!channelId)return;try{await api.deleteMessage(channelId,messageId)}catch(e){setError((e as Error).message)}}
  async function editMessage(message:Message){if(!channelId)return;const next=prompt('Mesajı düzenle',message.content);if(next===null||!next.trim()||next===message.content)return;setEditingId(message.id);try{await api.editMessage(channelId,message.id,next)}catch(e){setError((e as Error).message)}finally{setEditingId('')}}
  async function togglePin(messageId:string){if(!channelId)return;try{await api.togglePin(channelId,messageId)}catch(e){setError((e as Error).message)}}
  async function toggleReaction(message:Message,emoji:string){if(!channelId||!me)return;try{const mine=message.reactions?.find(r=>r.emoji===emoji)?.userIds.includes(me.id);if(mine)await api.unreactMessage(channelId,message.id,emoji);else await api.reactMessage(channelId,message.id,emoji)}catch(e){setError((e as Error).message)}}
  function addFiles(files:FileList|File[]){if(!canSendCurrent)return;const next=Array.from(files).filter(file=>file.size<=25*1024*1024).slice(0,10);setPendingFiles(previous=>[...previous,...next].slice(0,10));if(next.length<Array.from(files).length)setNotice('Bazı dosyalar 25 MB sınırı veya 10 dosya limiti nedeniyle eklenmedi.')}
  function selectChannel(id:string){setChannelId(id);setShowChannels(false);const target=server?.channels.find(item=>item.id===id);if(target?.type==='VOICE')void voice.join(id);else if(target?.type==='TEXT')clearUnread(id)}
  function selectServer(target:Server){setView('server');setServerId(target.id);setShowChannels(false);const first=target.channels.find(item=>item.type==='TEXT')||target.channels[0];setChannelId(first?.id||'');if(first?.type==='VOICE')void voice.join(first.id);else if(first?.type==='TEXT')clearUnread(first.id)}
  function changeDraft(value:string){if(!canSendCurrent)return;setDrafts(previous=>({...previous,[channelId]:value}));announceTyping(value)}
  async function send(e?:FormEvent){e?.preventDefault();if((!text.trim()&&!pendingFiles.length)||!channelId||sending||channel?.type!=='TEXT'||!canSendCurrent)return;const target=channelId;const content=text;const files=pendingFiles;const replyId=replyTo?.id;setSending(true);setError('');announceTyping('');try{const message=files.length?await api.uploadMessage(target,content,files,replyId):replyId?await api.sendMessage(target,content,replyId):await api.sendMessage(target,content);appendSent(message);clearUnread(target);setDrafts(previous=>previous[target]===content?{...previous,[target]:''}:previous);setPendingFiles([]);setReplyTo(null);if(fileInput.current)fileInput.current.value='';nearBottom.current=true}catch(e){setError((e as Error).message)}finally{setSending(false)}}
  async function joined(server:string){await refreshServers(server);setNotice('Sunucuya katıldın.');window.history.replaceState({},'','/');setPendingInvite('')}
  async function leave(){if(!server)return;await api.leaveServer(server.id);removeServerLocally(server.id,'left')}
  async function kick(userId:string){if(!server)return;await api.kickMember(server.id,userId)}
  async function refreshSocial(){const [friendList,requests,blockedList,dms]=await Promise.all([api.friends(),api.friendRequests(),api.blockedUsers(),api.dms()]);setFriends(friendList);setFriendRequests(requests);setBlocked(blockedList);setConversations(dms);void refreshDmUnreadCounts()}
  async function sendFriendRequest(username:string){await api.sendFriendRequest(username);await refreshSocial()}
  async function acceptFriendRequest(id:string){await api.acceptFriendRequest(id);await refreshSocial()}
  async function deleteFriendRequest(id:string){await api.deleteFriendRequest(id);await refreshSocial()}
  async function removeFriend(id:string){await api.removeFriend(id);await refreshSocial()}
  async function blockUser(id:string){await api.blockUser(id);if(activeDm?.other?.id===id)setActiveDmId('');await refreshSocial()}
  async function unblockUser(id:string){await api.unblockUser(id);await refreshSocial()}
  async function openDm(friendId:string){const conversation=await api.openDm(friendId);setConversations(previous=>[conversation,...previous.filter(item=>item.id!==conversation.id)]);setActiveDmId(conversation.id);setView('home');clearDmUnread(conversation.id)}
  async function createGroupDm(memberIds:string[],title?:string){const conversation=await api.createGroupDm(memberIds,title);setConversations(previous=>[conversation,...previous.filter(item=>item.id!==conversation.id)]);setActiveDmId(conversation.id);setView('home');clearDmUnread(conversation.id)}
  function changeDmDraft(value:string){setDmDrafts(previous=>({...previous,[activeDmId]:value}));announceDmTyping(value)}
  async function sendDm(files:File[]=[],replyToId?:string){if((!dmText.trim()&&!files.length)||!activeDmId||dmSending)return;const target=activeDmId;const content=dmText;setDmSending(true);setError('');announceDmTyping('');try{const message=files.length?await api.uploadDm(target,content,files,replyToId):replyToId?await api.sendDm(target,content,replyToId):await api.sendDm(target,content);appendDmSent(message);setDmDrafts(previous=>previous[target]===content?{...previous,[target]:''}:previous);setConversations(previous=>previous.map(item=>item.id===target?{...item,lastMessage:message,updatedAt:message.createdAt}:item).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)))}catch(e){setError((e as Error).message);throw e}finally{setDmSending(false)}}
  async function editDm(message:DirectMessage){const next=prompt('Mesajı düzenle',message.content);if(next===null||!next.trim()||next===message.content)return;try{await api.editDm(activeDmId,message.id,next)}catch(e){setError((e as Error).message)}}
  async function deleteDm(message:DirectMessage){if(!confirm('Bu mesaj herkesten silinsin mi?'))return;try{await api.deleteDm(activeDmId,message.id)}catch(e){setError((e as Error).message)}}
  async function pinDm(message:DirectMessage){try{await api.toggleDmPin(activeDmId,message.id)}catch(e){setError((e as Error).message)}}
  async function reactDm(message:DirectMessage,emoji:string){if(!me)return;try{const mine=message.reactions?.find(r=>r.emoji===emoji)?.userIds.includes(me.id);if(mine)await api.unreactDm(activeDmId,message.id,emoji);else await api.reactDm(activeDmId,message.id,emoji)}catch(e){setError((e as Error).message)}}

  function saveAppPreferences(next:AppPreferences){persistPreferences(next);setPreferences(next);setAppSettingsOpen(false);setNotice('Uygulama ayarları kaydedildi.')}

  if(!authed)return <AuthScreen inviteCode={pendingInvite} onAuth={()=>{setError('');setBooting(true);setAuthed(true)}}/>;
  if(booting&&!me)return <StartupScreen/>;
  if(bootError&&!me)return <StartupScreen error={bootError} onRetry={()=>setBootAttempt(value=>value+1)} onLogout={logout}/>;
  return <div className={`app-shell ${showChannels?'show-channels':''}`}>
    <aside className="serverbar" aria-label="Alanlar">
      <button className={view==='home'?'home active':'home'} title="Arkadaşlar ve özel mesajlar" aria-label="Arkadaşlar ve özel mesajlar" onClick={()=>{setView('home');setShowChannels(false)}}><span className="brand-mark">ST</span>{dmUnreadTotal+friendRequests.incoming.length>0&&<i className="workspace-badge home-attention">{Math.min(dmUnreadTotal+friendRequests.incoming.length,99)}</i>}</button>
      <div className="workspace-rule"/>
      {servers.map(s=>{
        const total=s.channels.reduce((sum,c)=>sum+(unread[c.id]?.count||0),0);
        const mentions=s.channels.reduce((sum,c)=>sum+(unread[c.id]?.mentions||0),0);
        return <button title={s.name} aria-label={s.name} key={s.id} className={view==='server'&&s.id===serverId?'server active':'server'} onClick={()=>selectServer(s)}><span>{s.name.slice(0,2).toUpperCase()}</span>{total>0&&<i className={mentions>0?'workspace-badge mention':'workspace-badge'}>{mentions>0?mentions:Math.min(total,99)}</i>}</button>
      })}
      <button title="Sunucu oluştur" aria-label="Sunucu oluştur" className="server add" onClick={()=>setModal({kind:'server'})}><Plus size={22}/></button>
    </aside>

    <aside className="channels">
      {view==='home'?<>
        <SocialSidebar conversations={conversations} activeConversationId={activeDmId} pendingCount={friendRequests.incoming.length} dmUnread={dmUnread} onFriends={()=>setActiveDmId('')} onOpen={id=>{setActiveDmId(id);clearDmUnread(id)}} onMarkAllRead={()=>void markAllDmRead()}/>
        <VoiceDock channelName={voiceChannelName} voice={voice}/>
        <div className="userbar">
          <button className="profile-launch" title="Profil kartı" aria-label="Profil kartı" onClick={()=>setProfileOpen(true)}>{me&&<Avatar user={me} online={socketOnline}/>}</button>
          <button className="userbar-copy" onClick={()=>setProfileOpen(true)}><b>{me?.displayName||me?.username||'Yükleniyor…'}</b><span><ProfileModeDot mode={me?.profileMode}/>{me?.statusText||profileModeLabel(me?.profileMode)}</span></button>
          <button className="icon-btn" title="Profili düzenle" aria-label="Profili düzenle" onClick={()=>setProfileOpen(true)}><UserRound size={18}/></button>
          <button className="icon-btn" title="Uygulama ayarları" aria-label="Uygulama ayarları" onClick={()=>setAppSettingsOpen(true)}><Settings size={18}/></button>
          <button className="icon-btn" title="Çıkış yap" aria-label="Çıkış yap" onClick={logout}><LogOut size={18}/></button>
        </div>
      </>:<>
        <header className="space-header"><div><small>AKTİF ALAN</small><span>{server?.name||'Alan oluştur'}</span></div><div className="space-head-actions">{server&&currentServerUnread>0&&<button className="icon-btn" title="Bu alandaki okunmamışları temizle" aria-label="Bu alandaki okunmamışları temizle" onClick={()=>void markServerRead()}><CheckCheck size={17}/></button>}{server&&<button className="icon-btn" title="Sunucu ayarları" aria-label="Sunucu ayarları" onClick={()=>setSettingsOpen(true)}><Settings size={17}/></button>}</div></header>
        <div className="channel-list">
          <div className="flow-create-row"><span>AKIŞLAR</span><div><button title="Metin kanalı oluştur" aria-label="Metin kanalı oluştur" disabled={!server||!can('MANAGE_CHANNELS')} onClick={()=>setModal({kind:'channel',initialType:'TEXT'})}><Hash size={14}/><Plus size={12}/></button><button title="Ses kanalı oluştur" aria-label="Ses kanalı oluştur" disabled={!server||!can('MANAGE_CHANNELS')} onClick={()=>setModal({kind:'channel',initialType:'VOICE'})}><Volume2 size={14}/><Plus size={12}/></button></div></div>
          {groupedChannels.map(group=><section className="flow-group" key={group.label}><div className="section">{group.label.toUpperCase()}</div>{group.channels.map(c=>{const activity=unread[c.id]||{count:0,mentions:0};return <button key={c.id} onClick={()=>selectChannel(c.id)} className={`${c.id===channelId?'channel active':'channel'} ${voice.channelId===c.id?'voice-connected':''}`}><span className="flow-icon">{c.type==='VOICE'?<Volume2 size={17}/>:<Hash size={17}/>}</span><span className="flow-name">{c.name}</span>{activity.mentions>0?<i className="unread-badge mention">@{Math.min(activity.mentions,99)}</i>:activity.count>0?<i className="unread-badge">{Math.min(activity.count,99)}</i>:null}</button>})}</section>)}
        </div>
        <VoiceDock channelName={voiceChannelName} voice={voice}/>
        <div className="userbar">
          <button className="profile-launch" title="Profil kartı" aria-label="Profil kartı" onClick={()=>setProfileOpen(true)}>{me&&<Avatar user={me} online={socketOnline}/>}</button>
          <button className="userbar-copy" onClick={()=>setProfileOpen(true)}><b>{me?.displayName||me?.username||'Yükleniyor…'}</b><span><ProfileModeDot mode={me?.profileMode}/>{me?.statusText||profileModeLabel(me?.profileMode)}</span></button>
          <button className="icon-btn" title="Profili düzenle" aria-label="Profili düzenle" onClick={()=>setProfileOpen(true)}><UserRound size={18}/></button>
          <button className="icon-btn" title="Uygulama ayarları" aria-label="Uygulama ayarları" onClick={()=>setAppSettingsOpen(true)}><Settings size={18}/></button>
          <button className="icon-btn" title="Çıkış yap" aria-label="Çıkış yap" onClick={logout}><LogOut size={18}/></button>
        </div>
      </>}
    </aside>

    <main className="chat">
      {view==='home'?(activeDm&&me?<DirectChat conversation={activeDm} me={me} messages={dmMessages} typingUsers={dmTypingUsers} loading={dmLoading} text={dmText} sending={dmSending} onText={changeDmDraft} onSend={sendDm} onCopy={content=>navigator.clipboard.writeText(content).then(()=>setNotice('Mesaj kopyalandı.')).catch(()=>setError('Pano erişimi yok.'))} onEdit={editDm} onDelete={deleteDm} onPin={pinDm} onReaction={reactDm}/>:<FriendsHome friends={friends} requests={friendRequests} blocked={blocked} onSend={sendFriendRequest} onAccept={acceptFriendRequest} onDeleteRequest={deleteFriendRequest} onOpenDm={openDm} onRemove={removeFriend} onBlock={blockUser} onUnblock={unblockUser} onCreateGroup={createGroupDm}/>):<>
        <header className="chat-head">
          <button className="icon-btn channel-toggle" aria-label="Kanalları göster" onClick={()=>setShowChannels(!showChannels)}><Menu size={20}/></button>
          <span className="flow-head-icon">{channel?.type==='VOICE'?<Volume2 size={18}/>:<Hash size={18}/>}</span>
          <div className="flow-head-copy"><b>{channel?.name||'akış seç'}</b><span>{channel?.type==='VOICE'?'Canlı ses akışı':'Yazılı sohbet akışı'}{channel?.groupName?` · ${channel.groupName}`:''}{channel?.type==='TEXT'&&(channel.slowModeSeconds||0)>0?` · Yavaş mod ${channel.slowModeSeconds} sn`:''}{channel?.type==='TEXT'&&channel.isLocked?' · KİLİTLİ':''}</span></div>
          <div className="chat-head-tools">{server&&<button className="icon-btn" title="Mesaj ara" aria-label="Mesaj ara" onClick={()=>setSearchOpen(true)}><Search size={17}/></button>}{channel?.type==='TEXT'&&(can('MANAGE_MESSAGES')||can('MANAGE_CHANNELS'))&&<div className="moderation-popover" onPointerDown={event=>event.stopPropagation()}><button className={moderationOpen?'icon-btn moderation-trigger active':'icon-btn moderation-trigger'} title="Moderasyon araçları" aria-label="Moderasyon araçları" aria-expanded={moderationOpen} onClick={event=>{event.stopPropagation();setModerationOpen(value=>!value)}}><ShieldCheck size={17}/><ChevronDown size={12}/></button>{moderationOpen&&<div className="moderation-menu" role="menu"><div className="moderation-menu-head"><ShieldCheck size={17}/><span><b>Akış moderasyonu</b><small>{channel.name}</small></span></div>{can('MANAGE_CHANNELS')&&<label className="moderation-menu-field">MESAJ ARALIĞI<select aria-label="Mesaj aralığı" value={channel.slowModeSeconds||0} disabled={!!actionBusy} onChange={event=>void changeSlowMode(Number(event.target.value))}><option value={0}>Kapalı</option><option value={5}>5 sn</option><option value={10}>10 sn</option><option value={30}>30 sn</option><option value={60}>1 dk</option><option value={120}>2 dk</option><option value={300}>5 dk</option><option value={600}>10 dk</option></select></label>}{can('MANAGE_CHANNELS')&&<button type="button" role="menuitem" disabled={!!actionBusy} onClick={()=>void toggleChannelLock()}>{channel.isLocked?<Unlock size={16}/>:<Lock size={16}/>}<span><b>{channel.isLocked?'Akış kilidini aç':'Akışı kilitle'}</b><small>{channel.isLocked?'Normal üyeler tekrar yazabilir.':'Normal üyelerin mesaj ve typing gönderimini durdur.'}</small></span></button>}{can('MANAGE_MESSAGES')&&<button type="button" role="menuitem" disabled={!!actionBusy} onClick={()=>void bulkDeleteMessages()}><Trash2 size={16}/><span><b>Son mesajları temizle</b><small>2–100 mesajı kalıcı olarak sil.</small></span></button>}{server&&server.channels.length>1&&can('MANAGE_CHANNELS')&&<button type="button" role="menuitem" className="danger-item" disabled={!!actionBusy} onClick={()=>void deleteChannel()}><Trash2 size={16}/><span><b>Kanalı sil</b><small>Akışı ve mesajlarını kalıcı olarak kaldır.</small></span></button>}</div>}</div>}<span className={socketOnline?'connection-pill online':'connection-pill offline'} title={socketOnline?'Gerçek zamanlı bağlantı aktif':'Bağlantı yeniden kuruluyor'}><i/>{socketOnline?'Canlı':'Bağlanıyor'}</span></div>
        </header>
        <section className={channel?.type==='VOICE'?'messages voice-section':'messages'} ref={scroll} aria-label="Mesajlar" onScroll={()=>{const el=scroll.current;if(el)nearBottom.current=el.scrollHeight-el.scrollTop-el.clientHeight<100}}>
          {channel?.type==='VOICE'?<VoicePanel channelId={channel.id} channelName={channel.name} voice={voice}/>:loading&&messages.length===0?<div className="message-skeleton" role="status">Mesajlar yükleniyor…</div>:messages.length===0?<div className="empty"><Hash size={42}/><h2>{channel?`${channel.name} akışının başlangıcı`:'ShakeChat’e hoş geldin'}</h2><p>{channel?'İlk mesajı sen gönder.':'Soldaki + düğmesiyle bir alan oluştur.'}</p></div>:messages.map(m=>{
            const ownMention=hasMention(m.content,me?.username);
            return <article id={`msg-${m.id}`} key={m.id} className={`${m.isPinned?'pinned-message ':''}${highlightMessageId===m.id?'search-highlight ':''}${ownMention?'mentioned-message':''}`.trim()}><Avatar user={m.author}/><div className="message-body">{m.replyTo&&<button className="reply-context" onClick={()=>document.getElementById(`msg-${m.replyTo?.id}`)?.scrollIntoView({behavior:'smooth',block:'center'})}><Reply size={13}/><b>{m.replyTo.author.displayName||m.replyTo.author.username}</b><span>{m.replyTo.content.slice(0,120)||'Dosya'}</span></button>}<div className="msg-meta"><b>{m.author.displayName||m.author.username}</b><time dateTime={m.createdAt} title={new Date(m.createdAt).toLocaleString('tr-TR')}>{new Date(m.createdAt).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})}</time>{m.editedAt&&<small>(düzenlendi)</small>}{ownMention&&<span className="mention-note"><AtSign size={11}/> sana</span>}{m.isPinned&&<span className="pin-badge"><Pin size={12}/> sabit</span>}</div>{m.content&&<p><MessageText content={m.content} currentUsername={me?.username}/></p>}{m.attachments?.length?<div className="attachments">{m.attachments.map(a=><div className="attachment" key={a.id}>{a.mimeType.startsWith('image/')?<a href={a.url} target="_blank" rel="noreferrer"><img src={a.url} alt={a.originalName}/></a>:a.mimeType.startsWith('video/')?<video src={a.url} controls preload="metadata"/>:<a href={a.url} target="_blank" rel="noreferrer"><Paperclip size={18}/><span>{a.originalName}<small>{(a.size/1024/1024).toFixed(1)} MB</small></span></a>}</div>)}</div>:null}{m.reactions?.length?<div className="reactions">{m.reactions.map(r=><button key={r.emoji} className={me&&r.userIds.includes(me.id)?'mine':''} onClick={()=>void toggleReaction(m,r.emoji)}>{r.emoji} {r.count}</button>)}</div>:null}</div><div className="message-actions"><button title="Mesajı kopyala" aria-label="Mesajı kopyala" onClick={()=>navigator.clipboard.writeText(m.content).then(()=>setNotice('Mesaj kopyalandı.')).catch(()=>setError('Pano erişimi yok. Mesajı seçip Ctrl+C kullan.'))}><Copy size={16}/></button><button title="Yanıtla" aria-label="Yanıtla" onClick={()=>{setReplyTo(m);composer.current?.focus()}}><Reply size={16}/></button><button title="Tepki ekle" aria-label="Tepki ekle" onClick={()=>void toggleReaction(m,'👍')}><SmilePlus size={16}/></button>{m.author.id===me?.id&&<button title="Mesajı düzenle" aria-label="Mesajı düzenle" disabled={editingId===m.id} onClick={()=>void editMessage(m)}><Pencil size={16}/></button>}{can('MANAGE_MESSAGES')&&<button title={m.isPinned?'Sabitlemeyi kaldır':'Mesajı sabitle'} aria-label="Mesajı sabitle" onClick={()=>void togglePin(m.id)}><Pin size={16}/></button>}{(m.author.id===me?.id||can('MANAGE_MESSAGES'))&&<button title="Mesajı sil" aria-label="Mesajı sil" onClick={()=>void deleteMessage(m.id)}><Trash2 size={16}/></button>}</div></article>
          })}
        </section>
        {channel?.type==='TEXT'&&<>
          {channel.isLocked&&<div className="channel-lock-banner"><Lock size={15}/><span>{canBypassChannelLock?'Bu akış kilitli. Moderasyon yetkin olduğu için yazabilirsin.':'Bu akış moderasyon tarafından geçici olarak kilitlendi.'}</span></div>}
          <div className="typing-line" role="status">{typingUsers.length?`${typingUsers.join(', ')} yazıyor…`:channel.isLocked&&!canBypassChannelLock?'Akış kilitli · moderasyon açana kadar mesaj gönderilemez':socketOnline?'Enter: gönder · Shift+Enter: yeni satır · dosya sürükleyebilirsin':'Bağlantı yeniden kuruluyor…'}</div>
          {replyTo&&<div className="reply-preview"><Reply size={15}/><span><b>{replyTo.author.displayName||replyTo.author.username}</b> kullanıcısına yanıt veriliyor: {replyTo.content.slice(0,90)||'Dosya'}</span><button aria-label="Yanıtı iptal et" onClick={()=>setReplyTo(null)}><X size={15}/></button></div>}
          {pendingFiles.length>0&&<div className="pending-files">{pendingFiles.map((file,index)=><div key={`${file.name}-${index}`}><Paperclip size={14}/><span>{file.name}</span><button aria-label="Dosyayı kaldır" onClick={()=>setPendingFiles(files=>files.filter((_,i)=>i!==index))}><X size={14}/></button></div>)}</div>}
          {mentionCandidates.length>0&&<div className="mention-suggestions"><span><AtSign size={14}/> Bahset</span>{mentionCandidates.map(member=><button type="button" key={member.id} onMouseDown={e=>e.preventDefault()} onClick={()=>insertMention(member.username)}><Avatar user={member} online={member.online}/><span><b>{member.displayName||member.username}</b><small>@{member.username}</small></span></button>)}</div>}
          <form className="composer media-composer" onSubmit={send} onDragOver={e=>{e.preventDefault();e.currentTarget.classList.add('dragging')}} onDragLeave={e=>e.currentTarget.classList.remove('dragging')} onDrop={e=>{e.preventDefault();e.currentTarget.classList.remove('dragging');addFiles(e.dataTransfer.files)}}><input ref={fileInput} hidden type="file" multiple onChange={e=>{if(e.target.files)addFiles(e.target.files)}}/><button type="button" className="attach-btn" aria-label="Dosya ekle" disabled={!canSendCurrent} onClick={()=>fileInput.current?.click()}><Paperclip size={19}/></button><textarea ref={composer} aria-label="Mesaj" rows={2} value={text} maxLength={4000} disabled={!canSendCurrent} onPaste={e=>{const files=Array.from(e.clipboardData.files);if(files.length)addFiles(files)}} onChange={e=>changeDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send()}}} placeholder={canSendCurrent?`${channel.name} akışına mesaj gönder`:channel.isLocked?'Bu akış kilitli':'Bu akışta mesaj gönderme yetkin yok'}/><button type="submit" aria-label="Mesaj gönder" disabled={sending||(!text.trim()&&!pendingFiles.length)||!canSendCurrent}><Send size={20}/></button></form>
        </>}
      </>}
    </main>

    <aside className="members">{view==='home'?(activeDm?<><div className="section">{activeDm.isGroup?'GRUP SOHBETİ':'ÖZEL MESAJ'}</div>{activeDm.isGroup?<div className="dm-profile group-profile"><div className="avatar group-avatar"><Users size={18}/></div><h3>{activeDm.title||'Grup sohbeti'}</h3><p>{activeDm.members.length} kişi</p><div className="group-member-list">{activeDm.members.map(member=><div key={member.id}><Avatar user={member} online={friends.find(friend=>friend.id===member.id)?.online}/><span>{member.displayName||member.username}{member.id===me?.id?' · Sen':''}</span></div>)}</div></div>:activeDm.other?<div className="dm-profile"><Avatar user={activeDm.other} online={friends.find(friend=>friend.id===activeDm.other?.id)?.online}/><h3>{activeDm.other.displayName||activeDm.other.username}</h3><p>@{activeDm.other.username}</p><small>{activeDm.other.statusText||profileModeLabel(activeDm.other.profileMode)}</small></div>:null}</>:<><div className="section">ARKADAŞLAR — {friends.length}</div>{friends.map(friend=><div className={`member ${friend.online?'':'offline'}`} key={friend.id}><Avatar user={friend} online={friend.online}/><div><b>{friend.displayName||friend.username}</b><small><ProfileModeDot mode={friend.profileMode}/>{friend.statusText||profileModeLabel(friend.profileMode)}</small></div></div>)}</>):[true,false].map(online=><div key={String(online)}><div className="section">{online?'ÇEVRİMİÇİ':'ÇEVRİMDIŞI'} — {members.filter(m=>m.online===online).length}</div>{members.filter(m=>m.online===online).map(m=><div className={`member ${m.online?'':'offline'}`} key={m.id}><Avatar user={m} online={m.online}/><div><b>{m.displayName||m.username}</b><small><ProfileModeDot mode={m.profileMode}/>{m.statusText||m.roles?.map(role=>role.name).join(' · ')||(m.role==='OWNER'?'Alan sahibi':m.role==='ADMIN'?'Yönetici':m.role==='MODERATOR'?'Moderatör':'Üye')}{m.id===me?.id?' · Sen':''}</small></div></div>)}</div>)}</aside>

    <AppToasts notice={notice} error={error} onDismissNotice={()=>setNotice('')} onDismissError={()=>setError('')}/>

    {modal&&<CreateModal modal={modal} onClose={()=>setModal(null)} onCreateServer={createServer} onCreateChannel={createChannel}/>} 
    {pendingInvite&&<InviteJoinModal code={pendingInvite} onClose={()=>{setPendingInvite('');window.history.replaceState({},'','/')}} onJoined={joined}/>} 
    {settingsOpen&&server&&me&&<ServerSettingsModal server={server} members={members} me={me} permissions={accessPermissions} onClose={()=>setSettingsOpen(false)} onLeave={leave} onKick={kick} onChanged={()=>{void reloadAccess()}}/>}
    {appSettingsOpen&&me&&<AppSettingsModal user={me} preferences={preferences} onClose={()=>setAppSettingsOpen(false)} onSave={saveAppPreferences} onNotice={message=>setNotice(message)} onSessionRenewed={(token,user)=>{auth.set(token);setMe(user);closeChatSocket();window.location.reload()}}/>}
    {profileOpen&&me&&<ProfileModal user={me} notificationsEnabled={notificationsEnabled} onToggleNotifications={toggleNotifications} onClose={()=>setProfileOpen(false)} onSaved={user=>{setMe(user);setNotice('Profil güncellendi.')}}/>}
    {searchOpen&&server&&<SearchPanel serverId={server.id} onClose={()=>setSearchOpen(false)} onPick={pickSearchResult}/>} 
  </div>;
}
