import React from 'react';
import ReactDOM from 'react-dom/client';
import { App } from './App';
import { GlobalUserContext } from './GlobalUserContext';
import { SidebarInteractions } from './SidebarInteractions';
import { VoiceSlotGuard } from './VoiceSlotGuard';
import { DomIdentityBridge } from './DomIdentityBridge';
import { MemberListUX } from './MemberListUX';
import { QuickSwitcher } from './QuickSwitcher';
import './styles.css';
import './shakechatbot-theme.css';
import './voice-theater.css';
import './user-context.css';
import './sidebar-context.css';
import './member-list-ux.css';
import './quick-switcher.css';
import './voice-realtime.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App /><GlobalUserContext /><SidebarInteractions /><VoiceSlotGuard /><DomIdentityBridge /><MemberListUX /><QuickSwitcher /></React.StrictMode>);