import { FormEvent, useEffect, useRef, useState } from 'react';
import { Ban, Check, CheckCheck, MessageCircle, Paperclip, Pencil, Pin, Reply, Search, SmilePlus, Trash2, UserMinus, UserPlus, Users, UsersRound, X } from 'lucide-react';
import { BlockedUser, DirectConversation, DirectMessage, Friend, FriendRequests, User } from './api';

function Avatar({user,online}:{user:User;online?:boolean}){
  return <div className={`avatar ${online?'online':''}`}>{user.avatarUrl?<img src={user.avatarUrl} alt="" onError={event=>{event.currentTarget.style.display='none'}}/>:(user.displayName||user.username).slice(0,2).toUpperCase()}</div>;
}

function conversationName(conversation:DirectConversation){
  if(!conversation.isGroup&&conversation.other)return conversation.other.displayName||conversation.other.username;
  if(conversation.title?.trim())return conversation.title.trim();
  return conversation.members.slice(0,3).map(user=>user.displayName||user.username).join(', ')||'Grup sohbeti';
}

function ConversationAvatar({conversation}:{conversation:DirectConversation}){
  if(!conversation.isGroup&&conversation.other)return <Avatar user={conversation.other}/>;
  return <div className="avatar group-avatar"><UsersRound size={18}/></div>;
}

export function SocialSidebar({conversations,activeConversationId,pendingCount,dmUnread,onFriends,onOpen,onMarkAllRead}:{
  conversations:DirectConversation[];activeConversationId:string;pendingCount:number;dmUnread:Record<string,number>;onFriends:()=>void;onOpen:(id:string)=>void;onMarkAllRead:()=>void;
}){
  const totalUnread=Object.values(dmUnread).reduce((sum,count)=>sum+count,0);
  return <><header className="social-head"><span>Özel Mesajlar</span>{totalUnread>0&&<button type="button" className="read-all-btn" title="Tüm özel mesajları okundu işaretle" aria-label="Tüm özel mesajları okundu işaretle" onClick={onMarkAllRead}><CheckCheck size={16}/><span>Okundu</span></button>}</header><div className="channel-list social-sidebar">
    <button className={!activeConversationId?'channel active':'channel'} onClick={onFriends}><Users size={18}/><span>Arkadaşlar</span>{pendingCount>0&&<b className="badge">{pendingCount}</b>}</button>
    <div className="section">ÖZEL MESAJLAR</div>
    {conversations.length===0?<p className="sidebar-empty">Henüz özel mesaj yok.</p>:conversations.map(conversation=>{const count=dmUnread[conversation.id]||0;return <button key={conversation.id} data-user-id={!conversation.isGroup&&conversation.other?conversation.other.id:undefined} className={conversation.id===activeConversationId?'dm-nav active':'dm-nav'} onClick={()=>onOpen(conversation.id)}><ConversationAvatar conversation={conversation}/><div><b>{conversationName(conversation)}</b><small>{conversation.isGroup?`${conversation.members.length} kişi · `:''}{conversation.lastMessage?.content||conversation.lastMessage?.attachments?.length?'Son etkinlik':'Mesaj başlat'}</small></div>{count>0&&<i className="dm-unread-badge">{Math.min(count,99)}</i>}</button>})}
  </div></>;
}

export function FriendsHome({friends,requests,blocked,onSend,onAccept,onDeleteRequest,onOpenDm,onRemove,onBlock,onUnblock,onCreateGroup}:{
  friends:Friend[];requests:FriendRequests;blocked:BlockedUser[];onSend:(username:string)=>Promise<void>;onAccept:(id:string)=>Promise<void>;onDeleteRequest:(id:string)=>Promise<void>;onOpenDm:(friendId:string)=>Promise<void>;onRemove:(friendId:string)=>Promise<void>;onBlock:(userId:string)=>Promise<void>;onUnblock:(userId:string)=>Promise<void>;onCreateGroup:(memberIds:string[],title?:string)=>Promise<void>;
}){
  const [username,setUsername]=useState(''); const [busy,setBusy]=useState(''); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
  const [groupOpen,setGroupOpen]=useState(false); const [groupTitle,setGroupTitle]=useState(''); const [groupMembers,setGroupMembers]=useState<string[]>([]);
  async function action(key:string,run:()=>Promise<void>){if(busy)return;setBusy(key);setError('');setNotice('');try{await run()}catch(e){setError((e as Error).message)}finally{setBusy('')}}
  async function submit(e:FormEvent){e.preventDefault();const value=username.trim();if(!value)return;await action('send',async()=>{await onSend(value);setUsername('');setNotice('Arkadaşlık isteği gönderildi.')})}
  async function createGroup(){if(groupMembers.length<2)return;await action('group',async()=>{await onCreateGroup(groupMembers,groupTitle.trim()||undefined);setGroupMembers([]);setGroupTitle('');setGroupOpen(false)})}
  return <div className="friends-home"><div className="friends-title"><Users size={26}/><div><h2>Arkadaşlar</h2><p>Arkadaş ekle, istekleri yönet, grup kur veya özel mesaj başlat.</p></div><button className="ghost-small" onClick={()=>setGroupOpen(value=>!value)}><UsersRound size={16}/> Grup sohbeti</button></div>
    {error&&<div className="error banner social-banner">{error}</div>}{notice&&<div className="notice social-notice">{notice}</div>}
    <form className="friend-add" onSubmit={submit}><div><label>KULLANICI ADI</label><div className="friend-search"><Search size={18}/><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Örn. aykut" maxLength={32}/></div></div><button className="primary compact" disabled={busy==='send'||!username.trim()}><UserPlus size={16}/> İstek gönder</button></form>

    {groupOpen&&<section className="social-section group-builder"><h3>YENİ GRUP SOHBETİ</h3><input value={groupTitle} onChange={e=>setGroupTitle(e.target.value)} maxLength={64} placeholder="Grup adı (isteğe bağlı)"/><div className="group-friend-grid">{friends.map(friend=><label key={friend.id}><input type="checkbox" checked={groupMembers.includes(friend.id)} onChange={()=>setGroupMembers(current=>current.includes(friend.id)?current.filter(id=>id!==friend.id):current.length<8?[...current,friend.id]:current)}/><Avatar user={friend} online={friend.online}/><span>{friend.displayName||friend.username}</span></label>)}</div><div className="role-actions"><button className="primary compact" disabled={groupMembers.length<2||!!busy} onClick={createGroup}><UsersRound size={16}/> Grubu aç ({groupMembers.length})</button><small>En az 2, en fazla 8 arkadaş seç.</small></div></section>}

    {requests.incoming.length>0&&<section className="social-section"><h3>GELEN İSTEKLER — {requests.incoming.length}</h3>{requests.incoming.map(request=><div className="social-row" data-user-id={request.user.id} key={request.id}><Avatar user={request.user}/><div className="grow"><b>{request.user.displayName||request.user.username}</b><small>@{request.user.username}</small></div><button className="ghost-small approve" disabled={!!busy} onClick={()=>action(`accept:${request.id}`,()=>onAccept(request.id))}><Check size={16}/> Kabul et</button><button className="ghost-small" disabled={!!busy} onClick={()=>action(`reject:${request.id}`,()=>onDeleteRequest(request.id))}><X size={16}/> Reddet</button><button className="ghost-small danger-text" disabled={!!busy} onClick={()=>action(`block:${request.user.id}`,()=>onBlock(request.user.id))}><Ban size={15}/> Engelle</button></div>)}</section>}

    {requests.outgoing.length>0&&<section className="social-section"><h3>GÖNDERİLEN İSTEKLER — {requests.outgoing.length}</h3>{requests.outgoing.map(request=><div className="social-row" data-user-id={request.user.id} key={request.id}><Avatar user={request.user}/><div className="grow"><b>{request.user.displayName||request.user.username}</b><small>Yanıt bekleniyor</small></div><button className="ghost-small" disabled={!!busy} onClick={()=>action(`cancel:${request.id}`,()=>onDeleteRequest(request.id))}><X size={16}/> İptal</button></div>)}</section>}

    <section className="social-section"><h3>ARKADAŞLAR — {friends.length}</h3>{friends.length===0?<div className="empty social-empty"><Users size={40}/><h3>Henüz arkadaşın yok</h3><p>Kullanıcı adıyla istek göndererek başlayabilirsin.</p></div>:friends.map(friend=><div className="social-row" data-user-id={friend.id} key={friend.id}><Avatar user={friend} online={friend.online}/><div className="grow"><b>{friend.displayName||friend.username}</b><small>{friend.online?'Çevrimiçi':'Çevrimdışı'} · @{friend.username}</small></div><button className="ghost-small" disabled={!!busy} onClick={()=>action(`dm:${friend.id}`,()=>onOpenDm(friend.id))}><MessageCircle size={16}/> Mesaj</button><button className="ghost-small danger-text" disabled={!!busy} onClick={()=>action(`block:${friend.id}`,()=>onBlock(friend.id))}><Ban size={15}/> Engelle</button><button className="ghost-small danger-text" disabled={!!busy} onClick={()=>action(`remove:${friend.id}`,()=>onRemove(friend.id))}><UserMinus size={16}/> Çıkar</button></div>)}</section>

    {blocked.length>0&&<section className="social-section"><h3>ENGELLENENLER — {blocked.length}</h3>{blocked.map(item=><div className="social-row" data-user-id={item.user.id} key={item.id}><Avatar user={item.user}/><div className="grow"><b>{item.user.displayName||item.user.username}</b><small>@{item.user.username}</small></div><button className="ghost-small" disabled={!!busy} onClick={()=>action(`unblock:${item.user.id}`,()=>onUnblock(item.user.id))}>Engeli kaldır</button></div>)}</section>}
  </div>;
}

export function DirectChat({conversation,me,messages,typingUsers,loading,text,sending,onText,onSend,onCopy,onEdit,onDelete,onPin,onReaction}:{
  conversation:DirectConversation;me:User;messages:DirectMessage[];typingUsers:string[];loading:boolean;text:string;sending:boolean;onText:(value:string)=>void;onSend:(files:File[],replyToId?:string)=>Promise<void>;onCopy:(text:string)=>void;onEdit:(message:DirectMessage)=>Promise<void>;onDelete:(message:DirectMessage)=>Promise<void>;onPin:(message:DirectMessage)=>Promise<void>;onReaction:(message:DirectMessage,emoji:string)=>Promise<void>;
}){
  const list=useRef<HTMLElement>(null); const fileInput=useRef<HTMLInputElement>(null); const [replyTo,setReplyTo]=useState<DirectMessage|null>(null); const [files,setFiles]=useState<File[]>([]);
  useEffect(()=>{if(list.current)list.current.scrollTop=list.current.scrollHeight},[conversation.id,messages.length,loading]);
  useEffect(()=>{setReplyTo(null);setFiles([])},[conversation.id]);
  function addFiles(incoming:FileList|File[]){setFiles(current=>[...current,...Array.from(incoming).filter(file=>file.size<=25*1024*1024)].slice(0,10))}
  async function submit(e?:FormEvent){e?.preventDefault();if(conversation.blocked||(!text.trim()&&!files.length)||sending)return;await onSend(files,replyTo?.id);setFiles([]);setReplyTo(null);if(fileInput.current)fileInput.current.value=''}
  const title=conversationName(conversation); const subtitle=conversation.isGroup?`${conversation.members.length} kişi`:conversation.other?`@${conversation.other.username}`:'';
  return <><header className="dm-header"><ConversationAvatar conversation={conversation}/><div><b>{title}</b><span>{subtitle}</span></div></header>
    <section ref={list} className="messages" aria-label="Özel mesajlar">{loading&&messages.length===0?<div className="message-skeleton">Mesajlar yükleniyor…</div>:messages.length===0?<div className="empty"><MessageCircle size={42}/><h2>{title} sohbeti</h2><p>Bu özel konuşmanın başlangıcı.</p></div>:messages.map(message=><article key={message.id} data-user-id={message.author.id} className={message.isPinned?'pinned-message':''}><Avatar user={message.author}/><div className="message-body">{message.replyTo&&<div className="reply-context"><Reply size={13}/><b>{message.replyTo.author.displayName||message.replyTo.author.username}</b><span>{message.replyTo.content.slice(0,120)||'Dosya'}</span></div>}<div className="msg-meta"><b>{message.author.id===me.id?'Sen':message.author.displayName||message.author.username}</b><time dateTime={message.createdAt}>{new Date(message.createdAt).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})}</time>{message.editedAt&&<small>(düzenlendi)</small>}{message.isPinned&&<span className="pin-badge"><Pin size={12}/> sabit</span>}</div>{message.content&&<p>{message.content}</p>}{message.attachments?.length?<div className="attachments">{message.attachments.map(a=><div className="attachment" key={a.id}>{a.mimeType.startsWith('image/')?<a href={a.url} target="_blank" rel="noreferrer"><img src={a.url} alt={a.originalName}/></a>:a.mimeType.startsWith('video/')?<video src={a.url} controls preload="metadata"/>:<a href={a.url} target="_blank" rel="noreferrer"><Paperclip size={18}/><span>{a.originalName}<small>{(a.size/1024/1024).toFixed(1)} MB</small></span></a>}</div>)}</div>:null}{message.reactions?.length?<div className="reactions">{message.reactions.map(r=><button key={r.emoji} className={r.userIds.includes(me.id)?'mine':''} onClick={()=>void onReaction(message,r.emoji)}>{r.emoji} {r.count}</button>)}</div>:null}</div><div className="message-actions"><button title="Mesajı kopyala" onClick={()=>onCopy(message.content)}>Kopyala</button><button title="Yanıtla" onClick={()=>setReplyTo(message)}><Reply size={15}/></button><button title="Tepki" onClick={()=>void onReaction(message,'👍')}><SmilePlus size={15}/></button>{message.author.id===me.id&&<button title="Düzenle" onClick={()=>void onEdit(message)}><Pencil size={15}/></button>}<button title={message.isPinned?'Sabitlemeyi kaldır':'Sabitle'} onClick={()=>void onPin(message)}><Pin size={15}/></button>{message.author.id===me.id&&<button title="Sil" className="danger-text" onClick={()=>void onDelete(message)}><Trash2 size={15}/></button>}</div></article>)}</section>
    <div className="typing-line" role="status">{typingUsers.length?`${typingUsers.join(', ')} yazıyor…`:'Enter: gönder · Shift+Enter: yeni satır · dosya sürükleyebilirsin'}</div>
    {replyTo&&<div className="reply-preview"><Reply size={15}/><span><b>{replyTo.author.displayName||replyTo.author.username}</b> kullanıcısına yanıt: {replyTo.content.slice(0,90)||'Dosya'}</span><button aria-label="Yanıtı iptal et" onClick={()=>setReplyTo(null)}><X size={15}/></button></div>}
    {files.length>0&&<div className="pending-files">{files.map((file,index)=><div key={`${file.name}-${index}`}><Paperclip size={14}/><span>{file.name}</span><button aria-label="Dosyayı kaldır" onClick={()=>setFiles(current=>current.filter((_,i)=>i!==index))}><X size={14}/></button></div>)}</div>}
    {conversation.blocked&&<div className="dm-blocked-note"><Ban size={15}/> Bu kullanıcıyla özel mesajlaşma engellenmiş. Geçmişi görebilirsin ama yeni mesaj gönderemezsin.</div>}
    <form className="composer media-composer" onSubmit={submit} onDragOver={e=>{e.preventDefault();e.currentTarget.classList.add('dragging')}} onDragLeave={e=>e.currentTarget.classList.remove('dragging')} onDrop={e=>{e.preventDefault();e.currentTarget.classList.remove('dragging');addFiles(e.dataTransfer.files)}}><input ref={fileInput} hidden type="file" multiple onChange={e=>{if(e.target.files)addFiles(e.target.files)}}/><button type="button" className="attach-btn" aria-label="Dosya ekle" disabled={conversation.blocked} onClick={()=>fileInput.current?.click()}><Paperclip size={19}/></button><textarea aria-label="Özel mesaj" rows={2} maxLength={4000} value={text} disabled={conversation.blocked} onPaste={e=>{const incoming=Array.from(e.clipboardData.files);if(incoming.length)addFiles(incoming)}} onChange={e=>onText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void submit()}}} placeholder={conversation.blocked?'Bu konuşmada yeni mesaj gönderilemez':`${title} sohbetine mesaj gönder`}/><button type="submit" disabled={conversation.blocked||sending||(!text.trim()&&!files.length)}>Gönder</button></form>
  </>;
}
